# Optimized workflow for building and deploying a VitePress site
name: Deploy Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # Single build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Build with VitePress (for GitHub Pages)
        run: pnpm docs:build --base /docs/
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .vitepress/dist
      - name: Build with VitePress (for FTP)
        run: pnpm docs:build
      - name: Upload FTP artifact
        uses: actions/upload-artifact@v4
        with:
          name: ftp-build
          path: .vitepress/dist/

  # Deploy to GitHub Pages
  deploy-gh-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy to GitHub Pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # Deploy to FTP (runs in parallel with GitHub Pages deployment)
  deploy-ftp:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy to FTP
    steps:
      - name: Download FTP build artifact
        uses: actions/download-artifact@v4
        with:
          name: ftp-build
          path: ./dist
      - name: Deploy to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**